{% set name = "vmprof" %}
{% set github_name = "vmprof-python" %}
{% set version = "0.4.12" %}
{% set sha256 = "c2a6bbf6e930d2174d01ae55ed21f419b5b4419ce05b2c92b8c8aac49dec49db" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ github_name }}-{{ version }}.tar.gz
  url: https://github.com/vmprof/vmprof-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - vmprofshow = vmprof.show:main

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - libunwind  # [linux]
  run:
    - python
    - requests
    - six
    - pytz
    - colorama
    - backports.shutil_which  # [py2k]
    - libunwind  # [linux]

test:
  imports:
    - vmprof
    - jitlog
    - vmshare
  commands:
    - vmprofshow --help
    - py.test vmprof/ -vrs
  requires:
    - pytest
    - cffi
    - hypothesis
    - toolchain
  source_files:
    - vmprof
    - src


about:
  home: https://github.com/vmprof/vmprof-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'vmprof - a statistical program profiler'

  description: |
    vmprof is a platform to understand and resolve performance bottlenecks in your code. 
    It includes a lightweight profiler for CPython 2.7, CPython 3 and PyPy and 
    an assembler log visualizer for PyPy. 
  doc_url: https://vmprof.readthedocs.io
  dev_url: https://github.com/vmprof/vmprof-python

extra:
  recipe-maintainers:
    - synapticarbors
