{% set name = "vmprof" %}
{% set version = "0.4.16" %}
{% set sha256 = "104784fa4a6b97b3a05317042652eb6b70ee6a998a830514d05208269440918f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmprof/vmprof-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patch/203.patch
    - patch/test.patch  # [osx]
    - patch/remove-Werror.patch  # [osx]
    - patch/244.patch  # [osx and arm64]
    - patch/aarch64.patch  # [arm64 or aarch64 or ppc64le]
    # These are probably unnecessary after 0.4.15:
    - patch/237.diff  # [ppc64le]
    - patch/239.diff  # [ppc64le]

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv  # [not (ppc64le or aarch64)]
    - LDFLAGS+=" -pthread" {{ PYTHON }} -m pip install . -vv  # [ppc64le or aarch64]
  entry_points:
    - vmprofshow = vmprof.show:main

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libunwind  # [linux]
  run:
    - python
    - requests
    - six
    - pytz
    - colorama
    - libunwind  # [linux]

test:
  imports:
    - vmprof
    - jitlog
    - vmshare
  commands:
    - vmprofshow --help
    - CC=$CC_FOR_BUILD py.test vmprof/ -vrs  # [not (ppc64le or aarch64 or win)]
    - py.test vmprof/ -vrs  # [win]
  requires:
    - {{ compiler('c') }}
    - pytest
    - cffi
    - hypothesis
  source_files:
    - vmprof
    - src


about:
  home: https://github.com/vmprof/vmprof-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'vmprof - a statistical program profiler'

  description: |
    vmprof is a platform to understand and resolve performance bottlenecks in your code.
    It includes a lightweight profiler for CPython 2.7, CPython 3 and PyPy and
    an assembler log visualizer for PyPy.
  doc_url: https://vmprof.readthedocs.io
  dev_url: https://github.com/vmprof/vmprof-python

extra:
  recipe-maintainers:
    - synapticarbors
    - matthiasdiener
