{% set name = "vmprof" %}
{% set version = "0.4.17" %}
{% set sha256 = "bfd1800b5c9520aff3790b7e0ee0b6086506f6d161bedc69135e306141ca7bac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmprof/vmprof-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv  # [not (ppc64le or aarch64)]
    - LDFLAGS+=" -pthread" {{ PYTHON }} -m pip install . -vv  # [ppc64le or aarch64]
  entry_points:
    - vmprofshow = vmprof.show:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libunwind  # [linux]
  run:
    - python
    - requests
    - six
    - pytz
    - colorama
    - libunwind  # [linux]

test:
  imports:
    - vmprof
    - jitlog
    - vmshare
  commands:
    - vmprofshow --help
    - CC=$CC_FOR_BUILD py.test vmprof/ -vrs  # [not (ppc64le or aarch64 or win)]
    - py.test vmprof/ -vrs  # [win]
  requires:
    - {{ compiler('c') }}
    - zlib
    - pytest
    - cffi
    - hypothesis
  source_files:
    - vmprof
    - src


about:
  home: https://github.com/vmprof/vmprof-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'vmprof - a statistical program profiler'

  description: |
    vmprof is a platform to understand and resolve performance bottlenecks in your code.
    It includes a lightweight profiler for CPython 2.7, CPython 3 and PyPy and
    an assembler log visualizer for PyPy.
  doc_url: https://vmprof.readthedocs.io
  dev_url: https://github.com/vmprof/vmprof-python

extra:
  recipe-maintainers:
    - synapticarbors
    - matthiasdiener
