{% set name = "vmprof" %}
{% set version = "0.4.15" %}
{% set sha256 = "39ec09f84df30e9af566d1eefe8d53bfd89758febd3336e73e3648d1556e4108" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmprof/vmprof-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patch/203.patch  # [osx]
    - patch/test.patch  # [osx]
    - patch/remove-Werror.patch  # [osx]
    - patch/244.patch  # [osx and arm64]

build:
  number: 2 
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - vmprofshow = vmprof.show:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - libunwind  # [linux]
  run:
    - python
    - requests
    - six
    - pytz
    - colorama
    - libunwind  # [linux]

test:
  imports:
    - vmprof
    - jitlog
    - vmshare
  commands:
    - vmprofshow --help
    - CC=$CC_FOR_BUILD py.test vmprof/ -vrs  # [not win]
    - py.test vmprof/ -vrs  # [win]
  requires:
    - {{ compiler('c') }}
    - pytest
    - cffi
    - hypothesis
  source_files:
    - vmprof
    - src


about:
  home: https://github.com/vmprof/vmprof-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'vmprof - a statistical program profiler'

  description: |
    vmprof is a platform to understand and resolve performance bottlenecks in your code.
    It includes a lightweight profiler for CPython 2.7, CPython 3 and PyPy and
    an assembler log visualizer for PyPy.
  doc_url: https://vmprof.readthedocs.io
  dev_url: https://github.com/vmprof/vmprof-python

extra:
  recipe-maintainers:
    - synapticarbors
    - matthiasdiener
