{% set name = "vmprof" %}
{% set version = "0.4.14" %}
{% set sha256 = "da11f028ab71ded25549387b663845f55ed29fb081443760cc8a33e9641fcdbe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vmprof/vmprof-python/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - vmprofshow = vmprof.show:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - libunwind  # [linux]
  run:
    - python
    - requests
    - six
    - pytz
    - colorama
    - backports.shutil_which  # [py2k]
    - libunwind  # [linux]

test:
  imports:
    - vmprof
    - jitlog
    - vmshare
  commands:
    - vmprofshow --help
    - py.test vmprof/ -vrs
  requires:
    - pytest
    - cffi
    - hypothesis
    - toolchain
  source_files:
    - vmprof
    - src


about:
  home: https://github.com/vmprof/vmprof-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'vmprof - a statistical program profiler'

  description: |
    vmprof is a platform to understand and resolve performance bottlenecks in your code. 
    It includes a lightweight profiler for CPython 2.7, CPython 3 and PyPy and 
    an assembler log visualizer for PyPy. 
  doc_url: https://vmprof.readthedocs.io
  dev_url: https://github.com/vmprof/vmprof-python

extra:
  recipe-maintainers:
    - synapticarbors
