appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: EmehtC4NXlt3twxoiWnbRZ2t58tO/4wTheQu5dPA97o2hXhmuVqVT6IWuFTKHg0c3jmPge9W/wstNsZ+YkYWty8HLyX6iHOXQrU2lJESVHFYQqS8sTEzY1l+fD1HyzqDv9LB4Kt13JdRiI6C38E6fhfitSIf6mGrbm5ADOteyQJqH00WaeLSyoMlDi03nNYoXA1ZfX6wizZvj3DOYPvBNX7c7KHECQ/qIL9ueEWYmolEvEtMBjqOV4DRVtJwDl3Gglc9COc/Y6FKgo9mAfmDq7fO1JOQwgyf1A8LwWCh7+1UWT7lUuUqSYnQmvyh4Q3zvh+N6vEegaxEC/33QChQPyxKor0QDeUEgdUjqKkyB4UYzh6YDMBzg6SlCrv5d2cm2LiDKpD87WQsUJtKr15WoOQwoJhmPJECIABB9WVli6Ee/UtZVlcD6ikvbL9L+LOsR25AqHZg+Q6zht476RpP8YDugqNGiF74K4s7iBtCJYdzQ8YvJxouD2s5Yt49TpRu82r0NZjP2IKVPSI+NoB0IpYbKh5vNY91VOgYIy+e/aY0U+zT9WZTtrPo0ZKb108YpzyfWs5p1qUawfx4fxq4LywjapfZvr7nFiRCdwF3zeFfltrBPxcj28WSV5k8evnMrFn3oHcEDCdA0D4WL1Y9sy5U+/iHVdIMSW6p8bM+UIs=}
